version: '3.8'

services:
  kora-server:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "6969:6969"
      - "5555:5555"
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - NODE_ENV=production
    restart: unless-stopped